Resources:
  
  SgNoWorldIngress:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: sg-no-world-ingress
      Description: Flags security groups with any ingress rule open to 0.0.0.0/0 or ::/0.
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::SecurityGroup
      Source:
        Owner: CUSTOM_LAMBDA
        SourceIdentifier: __RULE_LAMBDA_ARN__
        SourceDetails:
          - EventSource: aws.config
            MessageType: ConfigurationItemChangeNotification
          - EventSource: aws.config
            MessageType: OversizedConfigurationItemChangeNotification

  
  SgNoWorldIngressRestrictedPorts:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: sg-no-world-ingress-restricted-ports
      Description: Flags and auto-remediates security groups that open restricted ports to 0.0.0.0/0 or ::/0.
      InputParameters:
        restrictedPorts: "__RESTRICTED_PORTS__"
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::SecurityGroup
      Source:
        Owner: CUSTOM_LAMBDA
        SourceIdentifier: __RULE_LAMBDA_ARN__
        SourceDetails:
          - EventSource: aws.config
            MessageType: ConfigurationItemChangeNotification
          - EventSource: aws.config
            MessageType: OversizedConfigurationItemChangeNotification

  SgNoWorldIngressRestrictedPortsRemediation:
    Type: AWS::Config::RemediationConfiguration
    DependsOn: SgNoWorldIngressRestrictedPorts
    Properties:
      ConfigRuleName: sg-no-world-ingress-restricted-ports
      TargetType: SSM_DOCUMENT
      TargetId: __REMEDIATION_DOCUMENT_NAME__
      Automatic: __AUTOMATIC_REMEDIATION__
      MaximumAutomaticAttempts: 3
      RetryAttemptSeconds: 60
      Parameters:
        GroupId:
          ResourceValue:
            Value: RESOURCE_ID
        RestrictedPorts:
          StaticValue:
            Values:
              - "__RESTRICTED_PORTS__"
        AutomationAssumeRole:
          StaticValue:
            Values:
              - __REMEDIATION_ROLE_ARN__